name: Run tests

on:
  push:

jobs:
  lint:
    name: Test code base
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install --no-cache-dir -r requirements/prod.txt
        pip install --no-cache-dir -r requirements/test.txt
    - name: Run tests
      run: |
        make test
